# Generated by Django 6.0 on 2026-01-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержимое")),
                (
                    "preview",
                    models.ImageField(upload_to="preview/", verbose_name="Изображение"),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("publication", models.BooleanField(default=True)),
                ("views", models.IntegerField(verbose_name="Просмотры")),
            ],
            options={
                "verbose_name": "публикация",
                "verbose_name_plural": "публикации",
                "ordering": ["heading"],
            },
        ),
    ]
