# Generated by Django 6.0 on 2026-01-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="views",
            field=models.IntegerField(default=1, verbose_name="Просмотры"),
        ),
    ]
